import type { ResumeLanguage } from '../domain/ResumeData.ts';

/**
 * Interface strings for the resume builder, keyed by the `data-resume-i18n*`
 * attributes in `resume.html`. English is the fallback for any key a
 * translation has not covered.
 */
const COPY: Record<ResumeLanguage, Readonly<Record<string, string>>> = {
  en: {
    title: 'Resume Builder',
    personalInfo: 'Personal Info',
    design: 'Design',
    skills: 'Skills',
    workHistory: 'Work History',
    education: 'Education',
    languages: 'Languages',
    interests: 'Interests',
    exportImport: 'Export / Import',
    fullName: 'Full Name',
    jobTitle: 'Job Title',
    profilePhoto: 'Profile Photo',
    removePhoto: 'Remove Photo',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    summary: 'Professional Summary',
    accentColor: 'Accent Color',
    secondaryColor: 'Secondary Color',
    leftPanel: 'Left Panel',
    rightPanel: 'Right Panel',
    textColor: 'Text Color',
    mutedText: 'Muted Text',
    addSkill: 'Add Skill',
    addWork: 'Add Work Experience',
    addEducation: 'Add Education',
    addLanguage: 'Add Language',
    addInterest: 'Add Interest',
    exportJson: 'Export Resume JSON',
    importJson: 'Import Resume JSON',
    download: 'Download Resume as PDF',
    exportNote: 'Exports through browser print / Save as PDF to preserve selectable, searchable resume text for ATS and job portals.',
    skillsPreview: 'Skills',
    languagesPreview: 'Languages',
    interestsPreview: 'Interests',
    workHistoryPreview: 'Work history',
    educationPreview: 'Education',
    skillItem: 'Skill',
    languageItem: 'Language',
    interestItem: 'Interest or project',
    isProject: 'Is project?',
    workTitle: 'Job title',
    companyLocation: 'Company & location',
    startYear: 'Start year',
    endYear: 'End year',
    description: 'Description',
    degree: 'Degree / certificate',
    schoolLocation: 'School / university',
    removeItem: 'Remove item',
    removeInterest: 'Remove interest',
    removeEntry: 'Remove entry',
    projectLabel: 'Project:',
    current: 'Current',
  },
  ro: {
    title: 'Constructor CV',
    personalInfo: 'Informații personale',
    design: 'Design',
    skills: 'Competențe',
    workHistory: 'Experiență profesională',
    education: 'Educație',
    languages: 'Limbi',
    interests: 'Interese',
    exportImport: 'Export / Import',
    fullName: 'Nume complet',
    jobTitle: 'Titlu profesional',
    profilePhoto: 'Fotografie de profil',
    removePhoto: 'Elimină fotografia',
    phone: 'Telefon',
    email: 'E-mail',
    address: 'Adresă',
    summary: 'Rezumat profesional',
    accentColor: 'Culoare accent',
    secondaryColor: 'Culoare secundară',
    leftPanel: 'Panou stânga',
    rightPanel: 'Panou dreapta',
    textColor: 'Culoare text',
    mutedText: 'Text estompat',
    addSkill: 'Adaugă competență',
    addWork: 'Adaugă experiență',
    addEducation: 'Adaugă educație',
    addLanguage: 'Adaugă limbă',
    addInterest: 'Adaugă interes',
    exportJson: 'Exportă CV JSON',
    importJson: 'Importă CV JSON',
    download: 'Descarcă CV-ul ca PDF',
    exportNote: 'Exportă prin imprimarea browserului / Salvare ca PDF pentru a păstra textul selectabil și căutabil pentru ATS și portaluri de joburi.',
    skillsPreview: 'Competențe',
    languagesPreview: 'Limbi',
    interestsPreview: 'Interese',
    workHistoryPreview: 'Experiență profesională',
    educationPreview: 'Educație',
    skillItem: 'Competență',
    languageItem: 'Limbă',
    interestItem: 'Interes sau proiect',
    isProject: 'Este proiect?',
    workTitle: 'Titlu job',
    companyLocation: 'Companie și locație',
    startYear: 'An început',
    endYear: 'An sfârșit',
    description: 'Descriere',
    degree: 'Diplomă / certificat',
    schoolLocation: 'Școală / universitate',
    removeItem: 'Elimină elementul',
    removeInterest: 'Elimină interesul',
    removeEntry: 'Elimină intrarea',
    projectLabel: 'Proiect:',
    current: 'Prezent',
  },
};

export function resumeText(language: ResumeLanguage, key: string): string {
  return COPY[language][key] ?? COPY.en[key] ?? key;
}
